vim.pack.add({
  "https://github.com/tpope/vim-sleuth",
  "https://github.com/lewis6991/gitsigns.nvim",
  "https://github.com/echasnovski/mini.icons",
  "https://github.com/ibhagwan/fzf-lua",
  "https://github.com/stevearc/oil.nvim",
  "https://github.com/folke/which-key.nvim",
  "https://github.com/nvim-mini/mini.statusline",
})
